### ISSUE TITLE
Add support for RH sensor

### ISSUE THREAD

**Issue by DeeEmm** [DeeEmm/DIY-Flow-Bench#19]
Need to include RH measurements to allow correct conversion of Mass to Volumetric flow

Look at integration of DHT11 Sensor / Library

**Comment by DeeEmm** [comment]
Added support for DHT11 using simple DHT library - https://github.com/winlinvip/SimpleDHT

Need to test as sampling rate is 1khz so may need to delay read to every 2 secs or so

**Comment by ModchipMan** [comment]
Is Humidity displayed on LCD in some Menu..?

**Comment by DeeEmm** [comment]
No, but I've now added it to the menu. Will be included in next release.

Also fixed compilation error #23 DHT11 Won't compile

**Comment by DeeEmm** [comment]
Humidity now included in Build 20072901 using Adafruit BME280 combined sensor
