### ISSUE TITLE
[BUG]Large ACFM values with most recent build

### ISSUE THREAD

**Issue by KirikauKiwi** [DeeEmm/DIY-Flow-Bench#203]
Using Build 24110704

I don't have a MAF sensor connected, currently using a 10 kOhm trim pot, since updating to the latest build I now get very large ACFM values.
**MAF Voltage about 0.047V**
<img width="743" alt="Screenshot 2024-11-07 at 14 15 34" src="https://github.com/user-attachments/assets/d5db6547-7423-4d85-807f-7f9c14bb2539">

This is with the Audi RS4 MAF sensor defined and PRef is defined/active.
NO calibration or leak offsets have been applied. All set to zero. 

No config setting or such had been changed so remained the same as the previous build, but now I am seeing the very large ACFM numbers.

**Comment by KirikauKiwi** [comment]
Checking further MAF Flow KGH is also effected very large number displayed, Adjusted flow is blank

**Comment by DeeEmm** [comment]
Hmmnnn that is strange.

I am not seeing that here.

<img width="810" alt="Screenshot 2024-11-08 at 9 38 47 am" src="https://github.com/user-attachments/assets/47d13a0e-e986-4337-bf7f-d11b79d60305">

I cannot seem to replicate it for any combinations of values of pRef / MAF.

What do you have for version / hardware?

<img width="910" alt="Screenshot 2024-11-08 at 9 40 03 am" src="https://github.com/user-attachments/assets/20062b99-1485-4959-bfb6-56a9ef72fa7c">

**Comment by KirikauKiwi** [comment]
It appears I have something happening with my index.html file.

<img width="1105" alt="Screenshot 2024-11-08 at 00 31 05" src="https://github.com/user-attachments/assets/2222ca70-592e-4c65-87da-3f747e5d538b">

**Comment by DeeEmm** [comment]
The data circle elements are for the lift graph. It is a small dot that displays the point value when hovered over. It should be commented out. 

<img width="1400" alt="Screenshot 2024-11-08 at 11 14 19 am" src="https://github.com/user-attachments/assets/a79d2e2d-4b50-4380-80b7-e8d97ed5c7de">

But.... I was looking at this last week. Perhaps your index.html file is outdated?

Maybe try to re-upload the file from the repo's data folder

Or rename the file below and upload via the GUI (delete the old file first)

[index.html.txt](https://github.com/user-attachments/files/17671072/index.html.txt)

**Comment by DeeEmm** [comment]
There is one thing that I have noticed. I do not see the Adjusted Flow value update where the Depression is negative.

**Comment by KirikauKiwi** [comment]
Good spot with the adjusted flow.

I am back up and running now, I think you are correct somehow my index.html hadn't updated, looking in my file browser it was from four days ago.
Something was up with my computer, and it all fixed it self with a restart.

I am see the same as you know regarding the adjusted flow.

**Comment by KirikauKiwi** [comment]
The adjusted flow is working, it is not handling the negative value correctly, at least that's what I think.
If I adjust the slider I have to display a positive "Depression" on the GUI the "Adjusted Flow" appears.

https://github.com/user-attachments/assets/ed74816b-11d3-41e3-b38e-56dc545f1047

**Comment by KirikauKiwi** [comment]
Digging around I found in the structs.h
```
int adj_flow_depression = 28;                  // Adjusted flow depression in inches of water
```
If I change the 28 to -28, the adjusted flow will display for a negative depression and not for a positive depression, so it inverts problem.

Consulting my C++ guru that is ChatGPT it is telling me that in C++ it does not handle the square root of a negative number correctly.
```
scaleFactor = sqrt(pressureRatio);
```

Taking the absolute values for the pressure ratio appears to work. Will this break any other calculations that use the same conversion?
```
      pressureRatio = (abs(newPressure) / abs(oldPressure));
```
I am sure there is another way to handle this too, possibly with the <complex.h>

**Comment by stefan63** [comment]
Having similar issues. Plus an issue with Ref Press Sensor shows Not enabled (Using XGZP6899A010KPDPN) and sensor works and shows correct value.
![flow-rate](https://github.com/user-attachments/assets/26bbdbdd-1ba9-4b89-a978-9ee24555bba3)
![ref-press](https://github.com/user-attachments/assets/e30a1d3d-fb69-4956-9af9-510ff80b3a39)

**Comment by DeeEmm** [comment]
> Having similar issues. Plus an issue with Ref Press Sensor shows Not enabled (Using XGZP6899A010KPDPN) and sensor works and shows correct value.

The fix in @KirikauKiwi last PR addresses this. 

I will take a look at the sensor description. This should not effect the rest of the code.

**Comment by stefan63** [comment]
> > Having similar issues. Plus an issue with Ref Press Sensor shows Not enabled (Using XGZP6899A010KPDPN) and sensor works and shows correct value.
> 
> The fix in @KirikauKiwi last PR addresses this.
> 
> I will take a look at the sensor description. This should not effect the rest of the code.

I have like tryed to delete and reupload index.html about a million times. I finally tryed to remove all files in upload menu and then reboat the ESP and now I'm finally back in buisness. (Exept for that Diff Press Sensor information).

**Comment by DeeEmm** [comment]
ok I found an issue with the pressure sensor descriptions for the info pane.  The fixes are in with the SCFM code that I am working on. I will create  PR once the code has been properly tested.

**Comment by DeeEmm** [comment]
> I have like tryed to delete and reupload index.html about a million times. I finally tryed to remove all files in upload menu and then reboat the ESP and now I'm finally back in buisness. (Exept for that Diff Press Sensor information).

The trick is to go to the file dialog and delete the index.html file. It will then ask you to upload the new one.

If you try to upload without first deleting it, it will not overwrite the existing file

**Comment by stefan63** [comment]
That is the way I have done it. However it didn't work at that time.
Deleting all files and then reboot the board worked!?
ESP's can be hard to tame sometimes :)

Den lör 9 nov. 2024 kl 10:57 skrev Mick Percy ***@***.***>:

**Comment by DeeEmm** [comment]
This should be addressed in the latest PR. Let me know if this is still a problem.

Is this related to #217 ?

**Comment by DeeEmm** [comment]
Ok looks like this is a different issue to #217 so will close this out
