### ISSUE TITLE
[BUG]Flow Diff view on the DIYFB GUI

### ISSUE THREAD

**Issue by KirikauKiwi** [DeeEmm/DIY-Flow-Bench#211]
**Software Version**
- RELEASE V.2.0-RC.8
- Build 24110802
- 

**Describe the bug**
Should the three labels at the lower area of the "Flow Diff" match the first three labels from the configuration page Calibration Data, currently they do not.

It appears that all three of the Calibration Data offsets gets applied to the "Flow Rate" and "Adjusted Flow" as expected and only two of them appear to be applied to the "Flow Diff" the total numeric value is correct, but when you switch between the three options for "Flow Diff" the value only changes twice, I would expect it to change three time if there is data in all three of the calibration data.

Would it be useful to add the applied offset value to the text label that is displayed at the lower part of the "Flow Diff"
<img width="743" alt="Screenshot 2024-11-08 at 16 13 47" src="https://github.com/user-attachments/assets/ccc97fe6-c714-4bc0-ad97-09307e9c2add">
<img width="743" alt="Screenshot 2024-11-08 at 16 07 37" src="https://github.com/user-attachments/assets/4a950c04-aec7-4d58-9772-6f846e4dd2ff">

**Comment by KirikauKiwi** [comment]
LOL, got stuck and couldn't getting my head around it, but the penny dropped finally lol.

**Comment by KirikauKiwi** [comment]
I think I got caught as it looks like the "User Target" has not yet been full setup, is this correct?

**Comment by DeeEmm** [comment]
Flow targets were working, but I can see that now it is not.

Normally you click on the 'Unit' part of the tile to cycle through 'User target' / 'Leak Test' / 'Baseline'. 

Will take a look

**Comment by DeeEmm** [comment]
I can see the event triggering in the console and being received in the serial monitor...

<img width="209" alt="Screenshot 2024-11-09 at 11 36 11 am" src="https://github.com/user-attachments/assets/4b35ba93-5485-4290-9955-60d58448537a">

<img width="504" alt="Screenshot 2024-11-09 at 11 37 17 am" src="https://github.com/user-attachments/assets/898895ea-439a-4ba0-9489-705a3a12cfc5">

but I can also see an error...

<img width="593" alt="Screenshot 2024-11-09 at 11 45 56 am" src="https://github.com/user-attachments/assets/c3e50735-4777-42ef-b43d-e6b4403d9117">

I note that this is only happening for negative depression values so suspect related to that.

Will continue later this eve..

**Comment by KirikauKiwi** [comment]
I think I see the same as you on the screen.
What I think is happening is that on the dashboard page, when "Flow Diff, User Target (cfm)" is displayed where is it picking up its data value from? 

Because on the configuration page there in no field labeled "User Target", I only have "Baseline" and "Offset". 
Should there be a "User Target" field on the configuration page?

<img width="741" alt="Screenshot 2024-11-09 at 10 10 51" src="https://github.com/user-attachments/assets/81c31d4e-0af3-4c14-9769-9e1e737a93c0">

**Comment by DeeEmm** [comment]
Ahhh okay. 

To set the user target you need to click on the value in the tile...

https://github.com/user-attachments/assets/91107995-2d66-434f-a5fb-fa3927905bfc

I added this to the dashboard rather than the config as it is something that will likely get changed often. So this way it is quick to edit.

**Comment by KirikauKiwi** [comment]
It would be good I think to add the value of the offset to the view if possible on the dashboard page.

E.g. Currently its displays "Baseline (cfm)" I am suggesting to display  "Baseline (Value)(cfm)"

**Comment by KirikauKiwi** [comment]
> Ahhh okay.
> 
> To set the user target you need to click on the value in the tile...
> 
>  Screen.Recording.2024-11-09.at.8.51.58.pm.mov 
> 
> I added this to the dashboard rather than the config as it is something that will likely get changed often. So this way it is quick to edit.

Ahhhh so that is what I was missing, got it now 👍

**Comment by KirikauKiwi** [comment]
😂 I can confirm that it is all working as it should!!!!!! Now that I know what to do!!!!

Layer 1, User issue!!!!!!!!
