### ISSUE TITLE
Floating MAF voltage

### ISSUE THREAD

**Issue by DeeEmm** [DeeEmm/DIY-Flow-Bench#22]
MAF I/P showing 4v with no sensor disconnected.

Need to validate with sensor connected

**Comment by ModchipMan** [comment]
Im getting 3.42cfm with zero flow.

**Comment by DeeEmm** [comment]
Does it disappear if you add the following line to your Maf Data file
{0,0},

Add it above the other values

**Comment by ModchipMan** [comment]
added above to MAF Data file, still the same with weather change, it is now at 3.48cfm

**Comment by DeeEmm** [comment]
MAF decode now tested and stable
