### ISSUE TITLE
Maximum flow value for the graph scaling.

### ISSUE THREAD

**Issue by DeeEmm** [DeeEmm/DIY-Flow-Bench#220]
Together with valve lift interval can be added maximum flow value for the graph scaling.

_Originally posted by @black-top in https://github.com/DeeEmm/DIY-Flow-Bench/discussions/189#discussioncomment-11195707_

**Comment by DeeEmm** [comment]
@Stefan63 I've added ability to change Datagraph scale. The setting is in the configuration. Please check and let me know if this works for you

**Comment by black-top** [comment]
Scaling looks like it is working ok, but the flow numbers are now are completely wrong. Same setup, same cylinder head, all lift curve now read about 10-12CFM,  before at 13mm was 300CFM.
