### ISSUE TITLE
[FEATURE REQUEST]Suggested simplification of "Resolution and Accuracy" in GUI Configuration. 

### ISSUE THREAD

**Issue by KirikauKiwi** [DeeEmm/DIY-Flow-Bench#244]
I am suggesting a small change to the Resolution and Accuracy in the GUI Configuration page.

**From this**
<img width="717" alt="Screenshot 2024-11-20 at 00 05 41" src="https://github.com/user-attachments/assets/dfa5b4ad-b22d-469f-9dbc-51c43105ddc8">

**To this**
<img width="717" alt="Screenshot 2024-11-20 at 00 04 37" src="https://github.com/user-attachments/assets/e5c3ae0c-0cf1-4487-a192-f9df96259310">
<img width="717" alt="Screenshot 2024-11-20 at 00 04 52" src="https://github.com/user-attachments/assets/ad04f810-2594-4fd9-90d8-11d34c4d9cd1">

It is easier to understand and feels more intuitive for me. 
With these selections for Rounding and Decimal places on the GUI, does it only affect the displayed values, and not the data values used in the calculations etc.

**Comment by DeeEmm** [comment]
Ahh yes. Agreed. Makes more sense.

**Comment by DeeEmm** [comment]
It's funny. Had to look at the source for your post as the notification that I received showed that you had posted the HTML code.

Was scratching my head trying to work out how you managed to get the CSS from the project to work here in the forums.

😆🤣😆

**Comment by KirikauKiwi** [comment]
I did first try and post the HTML as I was not sure if it was possible to or not!!!, so I edited the comment and replaced the html with photos instead!!!!

**Comment by DeeEmm** [comment]
So changing the descriptions is trivial and done. However combining the decimal places with rounding is not so trivial.

We pass the decimal places directly to the GUI javascript via AJAX.

So, for FLOW_DECIMAL_LENGTH dropdown selection values...

- No DP = 0 
- 1 DP (0.1) = 1
- 2 DP (0.01) = 2

We pass this value directly to the GUI...

```
 document.getElementById(key).innerHTML = myObj[key].toFixed(~FLOW_DECIMAL_LENGTH~);  
```

So it is not possible to add an additional value for 0.5, even though this makes sense, as rounding and DP are different mathematical functions.

So the rounding and decimal places functions need to remain seperate for the time being as they apply to two different parts of the code.

I have changed the language as suggested for the DP drop-downs, and also changed the terminology of the rounding to further differentiate it from the DP to remove any ambiguity.

<img width="701" alt="Screenshot 2024-11-22 at 10 58 48 am" src="https://github.com/user-attachments/assets/64eef295-43fd-4c2b-bc60-281b3b7be96f">

<img width="669" alt="Screenshot 2024-11-22 at 10 58 38 am" src="https://github.com/user-attachments/assets/a4a6cb42-9c0d-41bb-8d31-2b5f08e06886">



We can of course revisit this down the track but given the amount of work still to do for RC9 I'm going to close this out for now.

**Comment by KirikauKiwi** [comment]
It amazes my that Human logic is often apparently simple, but at times still difficult in the binary world. I guess that is good for us Humans vs the Robots.

**Comment by KirikauKiwi** [comment]
The decimal point shift and the rounding are only happening at the GUI level, is that correct?

If so would a more approbate Heading for this section possibly be?
**Display Resolution**

**Comment by DeeEmm** [comment]
Yes only at the GUI level.  Rounding at the calc level just introduces error. 

The original intent is only to make it easier to read (for a human). i.e. to help prevent the rapid changing of fractional values in the GUI.

This effect does not impact data collection or API values as the data snapshot grabs all sensor data within a microsecond window. As such it is impervious to such change.
