### ISSUE TITLE
I2C devices not being found on boot

### ISSUE THREAD

**Issue by DeeEmm** [DeeEmm/DIY-Flow-Bench#248]
>Nice work, I have updated the relevant files and now get past the Initialising IO part of on the serial monitor, I am now encountering a problem that the I2C devices are not being found. It is showing the correct pins for my I2C.
I changed the files directly, I will fetch the latest DEV branch and try that incase I have missed something.
```
Multicast: http://diyfb.local 
Initialising I/O 
Input SDA_PIN: 8
Input SCL_PIN: 9
=== SPIFFS File system info === 
Total space:      1.26 MB 
Total space used: 60.54 KB 
Initialising Hardware 
Scanning for I2C devices...
Found 0 device(s). 
Initialising ADS1115 
[128700][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
ADS1115 Connection failed
```

_Originally posted by @KirikauKiwi in https://github.com/DeeEmm/DIY-Flow-Bench/issues/245#issuecomment-2491637603_

**Comment by DeeEmm** [comment]
Seems that error 263 is a timeout.

I guess check the obvious things initially...

- Wiring is correct / secure
- Pin numbers are correct
- Pull-up resistors installed

**Comment by KirikauKiwi** [comment]
My hardware is working on this version / build,
```
DIY Flow Bench 
Version: V.2.0-RC.8 
Build: 24111107 
Initialising Hardware 
Scanning for I2C devices...
Found address: 72 (0x48)
Found address: 118 (0x76)
Found 2 device(s). 
Initialising ADS1115 
ADS1115 Initialised
Hardware Initialised 
Initialising Sensors 
Initialising BME280 
BME280 Initialised
Sensors Initialised 
File System Initialisation...
Complete.
Creating config.json file... 
Creating liftdata.json file... 
Loading Configuration... 
Loading Lift Data... 
=== SPIFFS File system info === 
Total space:      1.26 MB 
Total space used: 2.45 KB 
```
- I have checked wiring is correct / secure as it works with a previous build. 
- The pins are correct and viewable on the serial monitor.
- I have the pinMode for the SDA and SCL set to INPUT_PULLUP in the data handler.cpp. as I don't have hardware pull-up resistors.

I tried changing the default structs.h from SDA_PIN = 99; int SCL_PIN = 99; to,  int SDA_PIN = 8;
  int SCL_PIN = 9; to check for a pin setting issue, I get the same serial monitor output either way.
```
DIY Flow Bench
DIYFB Version: V2.0.RC.8 
Build: 24112102 
For help please visit the WIKI:
https://github.com/DeeEmm/DIY-Flow-Bench/wiki
Initialising File System 
Loading Configuration 
Loading Lift Data 
Loading Calibration Data 
PINS file Found: /PINS_ESP32_S3_DEV_KITC.json
Loading Pins Data 
Parsing Pins Data 
Defaulting to AP Mode 
Creating WiFi Access Point:  DIYFB  
Access Point IP address: 192.168.4.1 
Multicast: http://diyfb.local 
Initialising I/O 
Input SDA_PIN: 8
Input SCL_PIN: 9
=== SPIFFS File system info === 
Total space:      1.26 MB 
Total space used: 61.28 KB 
Initialising Hardware 
Scanning for I2C devices...
Found 0 device(s). 
Initialising ADS1115 
[128706][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
ADS1115 Connection failed
```
The serial monitor gets to the "Scanning for I2C devices..." stage and after two minutes the "Initialising ADS1115.....Connection failed" appears.

**Comment by DeeEmm** [comment]
What happens if you comment out that section in the initaliseIO method?

```
  // if (pins.SDA_PIN < 99 ) {
  //   _message.serialPrintf("Input SDA_PIN: %d\n", pins.SDA_PIN );
  //   pinMode(pins.SDA_PIN, INPUT);   
  // }
  // if (pins.SCL_PIN < 99 ) {
  //   _message.serialPrintf("Input SCL_PIN: %d\n", pins.SCL_PIN );
  //   pinMode(pins.SCL_PIN, INPUT);   
  // }
```

**Comment by DeeEmm** [comment]
Don't really have any issues at all, which I believe is due to the environment.

I never call the Wemos D1 board configuration but use the generic esp32dev configuration. AFAIK this works on all ESP32's.

As soon as you define specific board configurations then you also pull in whatever configuration restrictions have been programmed in to the configuration, such as I/O restrictions.

The compiler just needs to know the compatible instruction set to be able to compile the code, it doesn't care about the rest of the stuff. BUT it will throw errors if there are conflicts with the board configuration at compile time.

Think of the esp32dev configuration as a bare minimum setup.

Have you tried to compile using the esp32dev environment and not calling any external frameworks?

**Comment by KirikauKiwi** [comment]
There doesn't appear too be a generic board version for the S3 variant of the ESP devices, I have looked through platformio and also attempted a few others with trail and error and when you run attempt to upload to the board it either say no such board or if you use esp32dev it reports back that you are using an esp32-s3.

The commenting out of the I2C pins has worked as the wire.begin(pins.SDA_PIN, pins.SCL_PIN) will be picking up the correct pins from the relevant pins.json file, so there must be some sort of issue with manually defining the pins and the automatic configuration that happens with the wire.begin() call.

This can be closed.

**Comment by DeeEmm** [comment]
> if you use esp32dev it reports back that you are using an esp32-s3

That's interesting. Seems like the S3 uses a different processor...

>Remember, an ESP32-S3 isn't an ESP32 MCU, despite it's name. The ESP32-S3 has an Extensa LX7 processor, while the original ESP32 has an Extensa LX6 processor.

Might explain this. Perhaps?

Did you reply to my message yet? Can you email me your mailing address. I'll send you a shield out for testing.

**Comment by DeeEmm** [comment]
I wonder if changing the MCU within the build environment would work...

```
board_build.mcu = esp32c3
```
