### ISSUE TITLE
[FEATURE REQUEST]Start/Stop GUI buttons

### ISSUE THREAD

**Issue by KirikauKiwi** [DeeEmm/DIY-Flow-Bench#252]
Are the "Start Bench", "Stop Bench" buttons on the GUI currently implemented?

**Comment by DeeEmm** [comment]
Yes, they currently control  'VAC_BANK_1_PIN' via Hardware::benchOn() which in turn controls the ULN2003 darlington array

The ULN2003 sinks the signal and requires an interposing 12v relay connected as follows...

12V (VCC)--------(85 )[ 12v relay coil ](86) --------X2_PIN_9
