### ISSUE TITLE
MPX4250 Ref Pressure Scaling error 

### ISSUE THREAD

**Issue by 930MAF** [DeeEmm/DIY-Flow-Bench#36]
When using the MPX4250 for pressure ref pin A2 i am seeing -43 at zero volts and 1044 at 4.8 volts.

**Arduino (please complete the following information):**
 - Firmware Version: Release V1 Beta Release #13 · Build 20080401
 - Hardware Type  Mega 2560 DFROBOT display

**Comment by DeeEmm** [comment]
refPressureKpa = (((refPressMillivolts / supplyMillivolts ) - 0.04) / 0.00369) - getBaroPressure(KPA);

**Comment by DeeEmm** [comment]
Added some additional code for dealing with the barometric offset in Build 20080704

**Comment by DeeEmm** [comment]
No further response so I'm going to mark this as closed.
